# Generated by Django 6.0.4 on 2026-04-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(max_length=20),
        ),
    ]
