# Generated by Django 6.0.4 on 2026-04-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loanapplication_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
