# Generated by Django 6.0.4 on 2026-04-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanapplication_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='document',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loanapplication')),
            ],
        ),
    ]
